name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/juliengriffoul/discord-cli

jobs:
  containerize:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Read version from VERSION file
      id: read_version
      run: |
        VERSION=$(cat VERSION)
        echo "Version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      id: build
      run: |
        docker build \
          -t ghcr.io/${{ github.repository }}:${{ env.version }} \
          -t ghcr.io/${{ github.repository }}:latest \
          .

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: 'ghcr.io/${{ github.repository }}:${{ env.version }}'
        format: 'table'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
        exit-code: '1'

    - name: Push Docker image
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        docker push ghcr.io/${{ github.repository }}:${{ env.version }}
        docker push ghcr.io/${{ github.repository }}:latest
